[theme]
theme = "gruvbox-dark"

# [[block]]
# block = "backlight"
# device = "intel_backlight"

[[block]]
block = "cpu"
interval = 1
format = " $barchart $utilization "

[[block]]
block = "memory"
# format = " $mem_used_percents.eng(w:1) "
format = " $mem_used.eng(w:3,u:B,p:M)/$mem_total.eng(w:2,u:B,p:M) $mem_used_percents.eng(w:2) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $available.eng(w:2) "

# [[block]]
# block = "net"
# format = "  $ssid"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d-%m-%Y %R:%S', l:en_US) "
